### ISSUE TITLE
Website - github pages

### ISSUE THREAD

**Issue by samuelorion** [osumontreal/OLS-2#18]
Renato asked if our website is using github pages since it is one of the [topics covered ](https://openlifesci.org/ols-2/schedule/#week-06)

#### Summary 
- No, it's on Gitlab https://github.com/osumontreal/OLS-2/issues/18#issuecomment-700251061
#### Decision / Conclusion
- Keep on Gitlab, will have documentation on how to contribute soon https://github.com/osumontreal/OLS-2/issues/18#issuecomment-700381398

**Comment by dannycolin** [comment]
No. It's hosted on GitLab. Back when Sam made it, we couldn't use GitHub Pages because it was only supporting Jekyll. However now that GitHub Actions exists, we could migrate it.

**Comment by samuelorion** [comment]
Not essential. Was just a question for our mentor. If you guys have a good solution set up – perfect. 

When we come to that phase of OLS-2, will learn about it ... but leave as is.

**Comment by samuelorion** [comment]
The only thing to consider is how straightforward will it be for non-technical people (me for example) to add new content / make mods to existing texts etc.,? If this is something that can be explained in a straightforward way in the contribution guide, perfect.

**Comment by dannycolin** [comment]
> The only thing to consider is how straightforward will it be for non-technical people (me for example) to add new content / make mods to existing texts etc.,?

If you know Markdown then you should be able to modify or add content. 

> If this is something that can be explained in a straightforward way in the contribution guide, perfect.

I'm definitely planning to add documentation on how to add content and even more.
