### ISSUE TITLE
Digital Ocean Hacktoberfest

### ISSUE THREAD

**Issue by anproulx** [osumontreal/OLS-2#21]
Discuss suggestion made by Renato to look into the Hacktoberfest.  Could help us getting outside interest 

#### Guidelines for Hacktoberfest
Register and make __four valid pull requests (PRs)__ between October 1-31 (in any time zone) to earn an Hacktoberfest tee or tree reward. PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest.  

More information : https://hacktoberfest.digitalocean.com/details/#maintainers)

**Comment by anproulx** [comment]
I am confused if Renato meant we should participate in it, or look at it as a way of bringing students/UdeM to participate in open science

**Comment by samuelorion** [comment]
> I am confused if Renato meant we should participate in it, or look at it as a way of bringing students/UdeM to participate in open science

Well, I think the idea was for both. A way to give OSUM some visibility in the open science / source world, and for us to participate in open projects (and get a tshirt / tree planted).

For me, given that expecting a baby this weekend, unsure. However, if have the time / energy, might participate. It could be interesting.
